name: Update and Restart Docker Container

on:
  push:
    branches:
      - main
    paths:
      - "*/"

jobs:
  update_and_restart_docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the main branch
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Stop and remove the running Docker container
      - name: Stop and remove running container
        run: |
          if [ $(docker ps -q --filter name=personal_website) ]; then
            docker stop personal_website
            docker rm personal_website
          else
            echo "No running container to stop."
          fi

      # Build the new Docker image
      - name: Build Docker image
        run: docker build -t personal_website:latest .

      # Start a new Docker container
      - name: Run new Docker container
        run: docker run -d --name personal_website -p 3000:3000 personal_website:latest
